"""题单定义：Hot100、剑指 Offer、Top Interview 150 等。

每个题单格式：[(题号, 题名, slug, 难度), ...]
"""

# ---------------------------------------------------------------------------
# LeetCode Hot 100
# ---------------------------------------------------------------------------

HOT100 = [
    (1, "两数之和", "two-sum", "简单"),
    (2, "两数相加", "add-two-numbers", "中等"),
    (3, "无重复字符的最长子串", "longest-substring-without-repeating-characters", "中等"),
    (4, "寻找两个正序数组的中位数", "median-of-two-sorted-arrays", "困难"),
    (5, "最长回文子串", "longest-palindromic-substring", "中等"),
    (11, "盛最多水的容器", "container-with-most-water", "中等"),
    (15, "三数之和", "3sum", "中等"),
    (17, "电话号码的字母组合", "letter-combinations-of-a-phone-number", "中等"),
    (19, "删除链表的倒数第N个结点", "remove-nth-node-from-end-of-list", "中等"),
    (20, "有效的括号", "valid-parentheses", "简单"),
    (21, "合并两个有序链表", "merge-two-sorted-lists", "简单"),
    (22, "括号生成", "generate-parentheses", "中等"),
    (23, "合并K个升序链表", "merge-k-sorted-lists", "困难"),
    (24, "两两交换链表中的节点", "swap-nodes-in-pairs", "中等"),
    (25, "K个一组翻转链表", "reverse-nodes-in-k-group", "困难"),
    (31, "下一个排列", "next-permutation", "中等"),
    (32, "最长有效括号", "longest-valid-parentheses", "困难"),
    (33, "搜索旋转排序数组", "search-in-rotated-sorted-array", "中等"),
    (34, "在排序数组中查找元素的第一个和最后一个位置", "find-first-and-last-position-of-element-in-sorted-array", "中等"),
    (39, "组合总和", "combination-sum", "中等"),
    (41, "缺失的第一个正数", "first-missing-positive", "困难"),
    (42, "接雨水", "trapping-rain-water", "困难"),
    (46, "全排列", "permutations", "中等"),
    (48, "旋转图像", "rotate-image", "中等"),
    (49, "字母异位词分组", "group-anagrams", "中等"),
    (53, "最大子数组和", "maximum-subarray", "中等"),
    (55, "跳跃游戏", "jump-game", "中等"),
    (56, "合并区间", "merge-intervals", "中等"),
    (62, "不同路径", "unique-paths", "中等"),
    (64, "最小路径和", "minimum-path-sum", "中等"),
    (70, "爬楼梯", "climbing-stairs", "简单"),
    (72, "编辑距离", "edit-distance", "中等"),
    (75, "颜色分类", "sort-colors", "中等"),
    (76, "最小覆盖子串", "minimum-window-substring", "困难"),
    (78, "子集", "subsets", "中等"),
    (79, "单词搜索", "word-search", "中等"),
    (84, "柱状图中最大的矩形", "largest-rectangle-in-histogram", "困难"),
    (85, "最大矩形", "maximal-rectangle", "困难"),
    (94, "二叉树的中序遍历", "binary-tree-inorder-traversal", "简单"),
    (96, "不同的二叉搜索树", "unique-binary-search-trees", "中等"),
    (98, "验证二叉搜索树", "validate-binary-search-tree", "中等"),
    (101, "对称二叉树", "symmetric-tree", "简单"),
    (102, "二叉树的层序遍历", "binary-tree-level-order-traversal", "中等"),
    (104, "二叉树的最大深度", "maximum-depth-of-binary-tree", "简单"),
    (105, "从前序与中序遍历序列构造二叉树", "construct-binary-tree-from-preorder-and-inorder-traversal", "中等"),
    (114, "二叉树展开为链表", "flatten-binary-tree-to-linked-list", "中等"),
    (121, "买卖股票的最佳时机", "best-time-to-buy-and-sell-stock", "简单"),
    (124, "二叉树中的最大路径和", "binary-tree-maximum-path-sum", "困难"),
    (128, "最长连续序列", "longest-consecutive-sequence", "中等"),
    (136, "只出现一次的数字", "single-number", "简单"),
    (139, "单词拆分", "word-break", "中等"),
    (141, "环形链表", "linked-list-cycle", "简单"),
    (142, "环形链表 II", "linked-list-cycle-ii", "中等"),
    (146, "LRU 缓存", "lru-cache", "中等"),
    (148, "排序链表", "sort-list", "中等"),
    (152, "乘积最大子数组", "maximum-product-subarray", "中等"),
    (155, "最小栈", "min-stack", "中等"),
    (160, "相交链表", "intersection-of-two-linked-lists", "简单"),
    (169, "多数元素", "majority-element", "简单"),
    (198, "打家劫舍", "house-robber", "中等"),
    (200, "岛屿数量", "number-of-islands", "中等"),
    (206, "反转链表", "reverse-linked-list", "简单"),
    (207, "课程表", "course-schedule", "中等"),
    (208, "实现 Trie (前缀树)", "implement-trie-prefix-tree", "中等"),
    (215, "数组中的第K个最大元素", "kth-largest-element-in-an-array", "中等"),
    (221, "最大正方形", "maximal-square", "中等"),
    (226, "翻转二叉树", "invert-binary-tree", "简单"),
    (234, "回文链表", "palindrome-linked-list", "简单"),
    (236, "二叉树的最近公共祖先", "lowest-common-ancestor-of-a-binary-tree", "中等"),
    (238, "除自身以外数组的乘积", "product-of-array-except-self", "中等"),
    (239, "滑动窗口最大值", "sliding-window-maximum", "困难"),
    (240, "搜索二维矩阵 II", "search-a-2d-matrix-ii", "中等"),
    (279, "完全平方数", "perfect-squares", "中等"),
    (283, "移动零", "move-zeroes", "简单"),
    (287, "寻找重复数", "find-the-duplicate-number", "中等"),
    (300, "最长递增子序列", "longest-increasing-subsequence", "中等"),
    (301, "删除无效的括号", "remove-invalid-parentheses", "困难"),
    (309, "最佳买卖股票时机含冷冻期", "best-time-to-buy-and-sell-stock-with-cooldown", "中等"),
    (312, "戳气球", "burst-balloons", "困难"),
    (322, "零钱兑换", "coin-change", "中等"),
    (337, "打家劫舍 III", "house-robber-iii", "中等"),
    (338, "比特位计数", "counting-bits", "简单"),
    (347, "前 K 个高频元素", "top-k-frequent-elements", "中等"),
    (394, "字符串解码", "decode-string", "中等"),
    (399, "除法求值", "evaluate-division", "中等"),
    (406, "根据身高重建队列", "queue-reconstruction-by-height", "中等"),
    (416, "分割等和子集", "partition-equal-subset-sum", "中等"),
    (437, "路径总和 III", "path-sum-iii", "中等"),
    (438, "找到字符串中所有字母异位词", "find-all-anagrams-in-a-string", "中等"),
    (448, "找到所有数组中消失的数字", "find-all-numbers-disappeared-in-an-array", "简单"),
    (461, "汉明距离", "hamming-distance", "简单"),
    (494, "目标和", "target-sum", "中等"),
    (538, "把二叉搜索树转换为累加树", "convert-bst-to-greater-tree", "中等"),
    (543, "二叉树的直径", "diameter-of-binary-tree", "简单"),
    (560, "和为 K 的子数组", "subarray-sum-equals-k", "中等"),
    (581, "最短无序连续子数组", "shortest-unsorted-continuous-subarray", "中等"),
    (617, "合并二叉树", "merge-two-binary-trees", "简单"),
    (621, "任务调度器", "task-scheduler", "中等"),
    (647, "回文子串", "palindromic-substrings", "中等"),
    (739, "每日温度", "daily-temperatures", "中等"),
    (763, "划分字母区间", "partition-labels", "中等"),
]

# ---------------------------------------------------------------------------
# 剑指 Offer（精选 75 题）
# ---------------------------------------------------------------------------

OFFER75 = [
    (3, "数组中重复的数字", "shu-zu-zhong-zhong-fu-de-shu-zi-lcof", "简单"),
    (4, "二维数组中的查找", "er-wei-shu-zu-zhong-de-cha-zhao-lcof", "中等"),
    (5, "替换空格", "ti-huan-kong-ge-lcof", "简单"),
    (6, "从尾到头打印链表", "cong-wei-dao-tou-da-yin-lian-biao-lcof", "简单"),
    (7, "重建二叉树", "zhong-jian-er-cha-shu-lcof", "中等"),
    (9, "用两个栈实现队列", "yong-liang-ge-zhan-shi-xian-dui-lie-lcof", "简单"),
    (10, "斐波那契数列", "fei-bo-na-qi-shu-lie-lcof", "简单"),
    (11, "旋转数组的最小数字", "xuan-zhuan-shu-zu-de-zui-xiao-shu-zi-lcof", "简单"),
    (12, "矩阵中的路径", "ju-zhen-zhong-de-lu-jing-lcof", "中等"),
    (13, "机器人的运动范围", "ji-qi-ren-de-yun-dong-fan-wei-lcof", "中等"),
    (14, "剪绳子", "jian-sheng-zi-lcof", "中等"),
    (15, "二进制中1的个数", "er-jin-zhi-zhong-1de-ge-shu-lcof", "简单"),
    (16, "数值的整数次方", "shu-zhi-de-zheng-shu-ci-fang-lcof", "中等"),
    (17, "打印从1到最大的n位数", "da-yin-cong-1dao-zui-da-de-nwei-shu-lcof", "简单"),
    (18, "删除链表的节点", "shan-chu-lian-biao-de-jie-dian-lcof", "简单"),
    (21, "调整数组顺序使奇数位于偶数前面", "diao-zheng-shu-zu-shun-xu-shi-qi-shu-wei-yu-ou-shu-qian-mian-lcof", "简单"),
    (22, "链表中倒数第k个节点", "lian-biao-zhong-dao-shu-di-kge-jie-dian-lcof", "简单"),
    (24, "反转链表", "fan-zhuan-lian-biao-lcof", "简单"),
    (25, "合并两个排序的链表", "he-bing-liang-ge-pai-xu-de-lian-biao-lcof", "简单"),
    (26, "树的子结构", "shu-de-zi-jie-gou-lcof", "中等"),
    (27, "二叉树的镜像", "er-cha-shu-de-jing-xiang-lcof", "简单"),
    (28, "对称的二叉树", "dui-cheng-de-er-cha-shu-lcof", "简单"),
    (29, "顺时针打印矩阵", "shun-shi-zhen-da-yin-ju-zhen-lcof", "简单"),
    (30, "包含min函数的栈", "bao-han-minhan-shu-de-zhan-lcof", "简单"),
    (31, "栈的压入、弹出序列", "zhan-de-ya-ru-dan-chu-xu-lie-lcof", "中等"),
    (32, "从上到下打印二叉树", "cong-shang-dao-xia-da-yin-er-cha-shu-lcof", "中等"),
    (33, "二叉搜索树的后序遍历序列", "er-cha-sou-suo-shu-de-hou-xu-bian-li-xu-lie-lcof", "中等"),
    (34, "二叉树中和为某一值的路径", "er-cha-shu-zhong-he-wei-mou-yi-zhi-de-lu-jing-lcof", "中等"),
    (35, "复杂链表的复制", "fu-za-lian-biao-de-fu-zhi-lcof", "中等"),
    (36, "二叉搜索树与双向链表", "er-cha-sou-suo-shu-yu-shuang-xiang-lian-biao-lcof", "中等"),
    (37, "序列化二叉树", "xu-lie-hua-er-cha-shu-lcof", "困难"),
    (38, "字符串的排列", "zi-fu-chuan-de-pai-lie-lcof", "中等"),
    (39, "数组中出现次数超过一半的数字", "shu-zu-zhong-chu-xian-ci-shu-chao-guo-yi-ban-de-shu-zi-lcof", "简单"),
    (40, "最小的k个数", "zui-xiao-de-kge-shu-lcof", "简单"),
    (42, "连续子数组的最大和", "lian-xu-zi-shu-zu-de-zui-da-he-lcof", "简单"),
    (46, "把数字翻译成字符串", "ba-shu-zi-fan-yi-cheng-zi-fu-chuan-lcof", "中等"),
    (47, "礼物的最大价值", "li-wu-de-zui-da-jie-zhi-lcof", "中等"),
    (48, "最长不含重复字符的子字符串", "zui-chang-bu-han-zhong-fu-zi-fu-de-zi-zi-fu-chuan-lcof", "中等"),
    (50, "第一个只出现一次的字符", "di-yi-ge-zhi-chu-xian-yi-ci-de-zi-fu-lcof", "简单"),
    (52, "两个链表的第一个公共节点", "liang-ge-lian-biao-de-di-yi-ge-gong-gong-jie-dian-lcof", "简单"),
    (53, "在排序数组中查找数字", "zai-pai-xu-shu-zu-zhong-cha-zhao-shu-zi-lcof", "简单"),
    (54, "二叉搜索树的第k大节点", "er-cha-sou-suo-shu-de-di-kda-jie-dian-lcof", "简单"),
    (55, "二叉树的深度", "er-cha-shu-de-shen-du-lcof", "简单"),
    (56, "数组中数字出现的次数", "shu-zu-zhong-shu-zi-chu-xian-de-ci-shu-lcof", "中等"),
    (57, "和为s的两个数字", "he-wei-sde-liang-ge-shu-zi-lcof", "简单"),
    (58, "翻转单词顺序", "fan-zhuan-dan-ci-shun-xu-lcof", "简单"),
    (59, "滑动窗口的最大值", "hua-dong-chuang-kou-de-zui-da-zhi-lcof", "困难"),
    (60, "n个骰子的点数", "nge-tou-zi-de-dian-shu-lcof", "中等"),
    (61, "扑克牌中的顺子", "bu-ke-pai-zhong-de-shun-zi-lcof", "简单"),
    (63, "股票的最大利润", "gu-piao-de-zui-da-li-run-lcof", "中等"),
    (64, "求1+2+…+n", "qiu-12n-lcof", "中等"),
    (65, "不用加减乘除做加法", "bu-yong-jia-jian-cheng-chu-zuo-jia-fa-lcof", "简单"),
    (66, "构建乘积数组", "gou-jian-cheng-ji-shu-zu-lcof", "中等"),
    (68, "二叉搜索树的最近公共祖先", "er-cha-sou-suo-shu-de-zui-jin-gong-gong-zu-xian-lcof", "简单"),
]

# ---------------------------------------------------------------------------
# Top Interview 150
# ---------------------------------------------------------------------------

TOP150 = [
    (1, "两数之和", "two-sum", "简单"),
    (2, "两数相加", "add-two-numbers", "中等"),
    (3, "无重复字符的最长子串", "longest-substring-without-repeating-characters", "中等"),
    (4, "寻找两个正序数组的中位数", "median-of-two-sorted-arrays", "困难"),
    (5, "最长回文子串", "longest-palindromic-substring", "中等"),
    (6, "N 字形变换", "zigzag-conversion", "中等"),
    (7, "整数反转", "reverse-integer", "中等"),
    (8, "字符串转换整数 (atoi)", "string-to-integer-atoi", "中等"),
    (9, "回文数", "palindrome-number", "简单"),
    (11, "盛最多水的容器", "container-with-most-water", "中等"),
    (13, "罗马数字转整数", "roman-to-integer", "简单"),
    (14, "最长公共前缀", "longest-common-prefix", "简单"),
    (15, "三数之和", "3sum", "中等"),
    (17, "电话号码的字母组合", "letter-combinations-of-a-phone-number", "中等"),
    (19, "删除链表的倒数第N个结点", "remove-nth-node-from-end-of-list", "中等"),
    (20, "有效的括号", "valid-parentheses", "简单"),
    (21, "合并两个有序链表", "merge-two-sorted-lists", "简单"),
    (22, "括号生成", "generate-parentheses", "中等"),
    (23, "合并K个升序链表", "merge-k-sorted-lists", "困难"),
    (25, "K个一组翻转链表", "reverse-nodes-in-k-group", "困难"),
    (26, "删除有序数组中的重复项", "remove-duplicates-from-sorted-array", "简单"),
    (27, "移除元素", "remove-element", "简单"),
    (28, "找出字符串中第一个匹配项的下标", "find-the-index-of-the-first-occurrence-in-a-string", "简单"),
    (30, "串联所有单词的子串", "substring-with-concatenation-of-all-words", "困难"),
    (33, "搜索旋转排序数组", "search-in-rotated-sorted-array", "中等"),
    (34, "在排序数组中查找元素的第一个和最后一个位置", "find-first-and-last-position-of-element-in-sorted-array", "中等"),
    (35, "搜索插入位置", "search-insert-position", "简单"),
    (36, "有效的数独", "valid-sudoku", "中等"),
    (42, "接雨水", "trapping-rain-water", "困难"),
    (45, "跳跃游戏 II", "jump-game-ii", "中等"),
    (46, "全排列", "permutations", "中等"),
    (48, "旋转图像", "rotate-image", "中等"),
    (49, "字母异位词分组", "group-anagrams", "中等"),
    (53, "最大子数组和", "maximum-subarray", "中等"),
    (54, "螺旋矩阵", "spiral-matrix", "中等"),
    (55, "跳跃游戏", "jump-game", "中等"),
    (56, "合并区间", "merge-intervals", "中等"),
    (57, "插入区间", "insert-interval", "中等"),
    (58, "最后一个单词的长度", "length-of-last-word", "简单"),
    (61, "旋转链表", "rotate-list", "中等"),
    (67, "二进制求和", "add-binary", "简单"),
    (68, "文本左右对齐", "text-justification", "困难"),
    (69, "x 的平方根", "sqrtx", "简单"),
    (70, "爬楼梯", "climbing-stairs", "简单"),
    (71, "简化路径", "simplify-path", "中等"),
    (73, "矩阵置零", "set-matrix-zeroes", "中等"),
    (74, "搜索二维矩阵", "search-a-2d-matrix", "中等"),
    (76, "最小覆盖子串", "minimum-window-substring", "困难"),
    (77, "组合", "combinations", "中等"),
    (80, "删除有序数组中的重复项 II", "remove-duplicates-from-sorted-array-ii", "中等"),
    (82, "删除排序链表中的重复元素 II", "remove-duplicates-from-sorted-list-ii", "中等"),
    (86, "分隔链表", "partition-list", "中等"),
    (88, "合并两个有序数组", "merge-sorted-array", "简单"),
    (92, "反转链表 II", "reverse-linked-list-ii", "中等"),
    (97, "交错字符串", "interleaving-string", "中等"),
    (98, "验证二叉搜索树", "validate-binary-search-tree", "中等"),
    (100, "相同的树", "same-tree", "简单"),
    (101, "对称二叉树", "symmetric-tree", "简单"),
    (104, "二叉树的最大深度", "maximum-depth-of-binary-tree", "简单"),
    (105, "从前序与中序遍历序列构造二叉树", "construct-binary-tree-from-preorder-and-inorder-traversal", "中等"),
    (106, "从中序与后序遍历序列构造二叉树", "construct-binary-tree-from-inorder-and-postorder-traversal", "中等"),
    (108, "将有序数组转换为二叉搜索树", "convert-sorted-array-to-binary-search-tree", "简单"),
    (112, "路径总和", "path-sum", "简单"),
    (114, "二叉树展开为链表", "flatten-binary-tree-to-linked-list", "中等"),
    (117, "填充每个节点的下一个右侧节点指针 II", "populating-next-right-pointers-in-each-node-ii", "中等"),
    (121, "买卖股票的最佳时机", "best-time-to-buy-and-sell-stock", "简单"),
    (122, "买卖股票的最佳时机 II", "best-time-to-buy-and-sell-stock-ii", "中等"),
    (124, "二叉树中的最大路径和", "binary-tree-maximum-path-sum", "困难"),
    (125, "验证回文串", "valid-palindrome", "简单"),
    (127, "单词接龙", "word-ladder", "困难"),
    (128, "最长连续序列", "longest-consecutive-sequence", "中等"),
    (129, "求根节点到叶节点数字之和", "sum-root-to-leaf-numbers", "中等"),
    (130, "被围绕的区域", "surrounded-regions", "中等"),
    (131, "分割回文串", "palindrome-partitioning", "中等"),
    (133, "克隆图", "clone-graph", "中等"),
    (134, "加油站", "gas-station", "中等"),
    (135, "分发糖果", "candy", "困难"),
    (136, "只出现一次的数字", "single-number", "简单"),
    (137, "只出现一次的数字 II", "single-number-ii", "中等"),
    (138, "随机链表的复制", "copy-list-with-random-pointer", "中等"),
    (139, "单词拆分", "word-break", "中等"),
    (141, "环形链表", "linked-list-cycle", "简单"),
    (146, "LRU 缓存", "lru-cache", "中等"),
    (148, "排序链表", "sort-list", "中等"),
    (150, "逆波兰表达式求值", "evaluate-reverse-polish-notation", "中等"),
    (151, "反转字符串中的单词", "reverse-words-in-a-string", "中等"),
    (152, "乘积最大子数组", "maximum-product-subarray", "中等"),
    (153, "寻找旋转排序数组中的最小值", "find-minimum-in-rotated-sorted-array", "中等"),
    (155, "最小栈", "min-stack", "中等"),
    (162, "寻找峰值", "find-peak-element", "中等"),
    (167, "两数之和 II", "two-sum-ii-input-array-is-sorted", "中等"),
    (169, "多数元素", "majority-element", "简单"),
    (172, "阶乘后的零", "factorial-trailing-zeroes", "中等"),
    (189, "轮转数组", "rotate-array", "中等"),
    (190, "颠倒二进制位", "reverse-bits", "简单"),
    (191, "位1的个数", "number-of-1-bits", "简单"),
    (198, "打家劫舍", "house-robber", "中等"),
    (199, "二叉树的右视图", "binary-tree-right-side-view", "中等"),
    (200, "岛屿数量", "number-of-islands", "中等"),
    (201, "数字范围按位与", "bitwise-and-of-numbers-range", "中等"),
    (202, "快乐数", "happy-number", "简单"),
    (205, "同构字符串", "isomorphic-strings", "简单"),
    (206, "反转链表", "reverse-linked-list", "简单"),
    (207, "课程表", "course-schedule", "中等"),
    (208, "实现 Trie (前缀树)", "implement-trie-prefix-tree", "中等"),
    (209, "长度最小的子数组", "minimum-size-subarray-sum", "中等"),
    (210, "课程表 II", "course-schedule-ii", "中等"),
    (211, "添加与搜索单词", "design-add-and-search-words-data-structure", "中等"),
    (212, "单词搜索 II", "word-search-ii", "困难"),
    (215, "数组中的第K个最大元素", "kth-largest-element-in-an-array", "中等"),
    (219, "存在重复元素 II", "contains-duplicate-ii", "简单"),
    (221, "最大正方形", "maximal-square", "中等"),
    (222, "完全二叉树的节点个数", "count-complete-tree-nodes", "简单"),
    (224, "基本计算器", "basic-calculator", "困难"),
    (226, "翻转二叉树", "invert-binary-tree", "简单"),
    (228, "汇总区间", "summary-ranges", "简单"),
    (230, "二叉搜索树中第K小的元素", "kth-smallest-element-in-a-bst", "中等"),
    (236, "二叉树的最近公共祖先", "lowest-common-ancestor-of-a-binary-tree", "中等"),
    (238, "除自身以外数组的乘积", "product-of-array-except-self", "中等"),
    (242, "有效的字母异位词", "valid-anagram", "简单"),
    (274, "H 指数", "h-index", "中等"),
    (289, "生命游戏", "game-of-life", "中等"),
    (290, "单词规律", "word-pattern", "简单"),
    (300, "最长递增子序列", "longest-increasing-subsequence", "中等"),
    (322, "零钱兑换", "coin-change", "中等"),
    (380, "O(1) 时间插入、删除和获取随机元素", "insert-delete-getrandom-o1", "中等"),
    (383, "赎金信", "ransom-note", "简单"),
    (399, "除法求值", "evaluate-division", "中等"),
    (427, "建立四叉树", "construct-quad-tree", "中等"),
    (433, "最小基因变化", "minimum-genetic-mutation", "中等"),
    (452, "用最少数量的箭引爆气球", "minimum-number-of-arrows-to-burst-balloons", "中等"),
    (530, "二叉搜索树的最小绝对差", "minimum-absolute-difference-in-bst", "简单"),
]

# ---------------------------------------------------------------------------
# 题单注册表
# ---------------------------------------------------------------------------

PROBLEM_LISTS = {
    "hot100": {"name": "LeetCode Hot 100", "name_en": "LeetCode Hot 100", "problems": HOT100},
    "offer75": {"name": "剑指 Offer 75", "name_en": "Sword Offer 75", "problems": OFFER75},
    "top150": {"name": "Top Interview 150", "name_en": "Top Interview 150", "problems": TOP150},
}

DEFAULT_LIST = "hot100"


def get_problem_list(list_id: str = "") -> list:
    """返回指定题单的题目列表。"""
    if not list_id:
        list_id = DEFAULT_LIST
    entry = PROBLEM_LISTS.get(list_id, PROBLEM_LISTS[DEFAULT_LIST])
    return entry["problems"]


def get_slug_category(list_id: str = "") -> dict:
    """根据题单生成 slug -> 分类 映射。"""
    from .init_plan import SLUG_CATEGORY
    # SLUG_CATEGORY 已有 Hot100 的映射，其他题单暂时返回 "其他"
    return SLUG_CATEGORY
